### ISSUE TITLE
Become a contributor

### ISSUE THREAD

**Issue by polytan02** [YunoHost-Apps/thelounge_ynh#1]
Hi everybody,

I would like to be able to update the packaging of the lounge to be compliant with YnH 2.5 and (try to) respect the lastest YEP.

Please may I kindly ask to become a contributor ? @Kloadut @abeudin @JocelynDelalande

**Comment by JocelynDelalande** [comment]
@polytan02 I'm not a maintainer, I'm (happily) discovering that the lounge fork has been packaged for ynh :-)).

**Comment by astorije** [comment]
Hey there! Happy to discover this repo as well 😄
Just FYI, I have re-added YunoHost to [this list](https://github.com/thelounge/lounge/wiki/Alternative-Install-methods). It will soon be ported to the main website in an "unofficial installs" section, so I can only wish this repo to get traction!
