### ISSUE TITLE
Upgrade to The Lounge 2.2.1

### ISSUE THREAD

**Issue by astorije** [YunoHost-Apps/thelounge_ynh#2]
It looks like this repo is currently packaging The Lounge v2.1.0.
v2.2.0 was released recently, quickly followed by v2.2.1.

See what you're missing at:

- https://github.com/thelounge/lounge/releases/tag/v2.2.0
- https://github.com/thelounge/lounge/releases/tag/v2.2.1

😄

**Comment by polytan02** [comment]
I have updated the app to get the latest version but I struggle installing npm/nodejs (it fails as version are outdated)

https://github.com/polytan02/thelounge_ynh

Once it will work I would like to merge into https://github.com/YunoHost-Apps/thelounge_ynh

**Comment by polytan02** [comment]
So, feel free to test the package [thelounge_ynh](https://github.com/polytan02/thelounge_ynh) : it installs fine but the app doesn't work : I get error 502 Bad Gateway

**Comment by astorije** [comment]
Hey @polytan02,

Sorry but I would not be the right person to test this as I'm not a YunoHost user (I am a maintainer of The Lounge).
Maybe @JocelynDelalande could help you?

However, I highly suggest you install from our official npm releases instead of git tags if possible, as releases come prebuilt and do not require you to install `devDependencies`.
