### ISSUE TITLE
Upgrade to 4.2.0

### ISSUE THREAD

**Issue by KWeaver87** [YunoHost-Apps/thelounge_ynh#27]
See https://github.com/thelounge/thelounge/releases/tag/v4.2.0

**Comment by KWeaver87** [comment]
Ah, I see that this is already merged into testing in #26. Any estimate on that getting pushed to Master?

**Comment by Rafi594** [comment]
Merged in master https://github.com/YunoHost-Apps/thelounge_ynh/commit/43bb8b2ed923b3b0fcc2f655f379a5fe3950937c
