### ISSUE TITLE
502 Bad Gateway after install

### ISSUE THREAD

**Issue by made42** [YunoHost-Apps/thelounge_ynh#3]
The Lounge for Yunohost is giving me a `502 Bad Gateway` after install.
I noticed that The Lounge's service status is listed as 
> thelounge: 
>   loaded: not-found
>   status: inactive

I can successfully start the service, but it's listed status doesn't change.

**Comment by lapineige** [comment]
Same behaviour for my part.

Service fails to start:
> Starting The Lounge IRC client...
thelounge.service start request repeated too quickly, refusing to start.
 Failed to start The Lounge IRC client.

**Comment by Rafi594** [comment]
Fixed by 96c93868ede679be1d6e661a9ffab1606032b8eb
