### ISSUE TITLE
Default user?

### ISSUE THREAD

**Issue by pr0fsmith** [YunoHost-Apps/thelounge_ynh#47]
I successfully install thelounge in yunohost but I got no dialogues for creating a user.  I tried running 'thelounge' commands in the the cli but it says command not found.  Am I missing something?

**Comment by ericgaspar** [comment]
LDAP is working for Thelounge so all the registered YunoHost users can automatically connect.
We are installing thelounge with NPM. that means that there is no binary created (so you can't use thelounge command).
You can edit the user configuration file : https://thelounge.chat/docs/users#editing-a-user-configuration-file
