### ISSUE TITLE
Installation of The Lounge fails with "NODE_ENV=production: command not found"

### ISSUE THREAD

**Issue by michalrudowicz** [YunoHost-Apps/thelounge_ynh#49]
### Describe the bug

Installation of The Lounge fails with `NODE_ENV=production: command not found` error in the install log.

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 4.3.4.1
- I have access to my server: Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 4.2.0~ynh5

### Steps to reproduce

- Try to install The Lounge with default settings
- After a while the process fails.

### Expected behavior

Installation finishes without errors

### Logs

https://paste.yunohost.org/raw/idarapukez

**Comment by ericgaspar** [comment]
Should be fixed with #46
